project:
  type: website
  output-dir: docs

engine: jupyter
execute:
  echo: false
  warning: false
  error: false

format:
  html:
    toc: true

website:
  title: "Lab Visualización — Afiliados 2025"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: visualizaciones_afiliados.qmd
        text: Visualizaciones
